### ISSUE TITLE
!홀짝 기능 시 0보다 작은 금액 베팅 가능

### ISSUE THREAD

**Issue by Achelous1** [dev-manager/discordy#4]
예)
`!홀짝 홀 -10000` 
맞출 경우 `본인 소지금` -10000원
틀릴 경우 `본인 소지금` +10000원

* 마이너스 금액일 경우 금액에 제한이 없어 게임 밸런스에 심각한 영향을 미침
예)
본인 소지금 : 10000원
`!홀짝 홀 100000` 일 경우 본인 소지금 보다 높기 때문에 에러발생
`!홀짝 홀 -1000000000000`일 경우 본인 소지금 보다 낮기 때문에 에러발생 안함

**Comment by dev-manager** [comment]
<h1>해결!</h1>
