### ISSUE TITLE
`!확률` 명령어 시 확률숫자 반올림 필요

### ISSUE THREAD

**Issue by Achelous1** [dev-manager/discordy#5]
![KakaoTalk_20210503_174557151](https://user-images.githubusercontent.com/24582045/116857333-92bd7280-ac37-11eb-90ff-d615344de24f.jpg)

`!확률` 명령어 시 홀짝 확률이 반올림이 되지 않아 보기 불편
소숫점 둘째자리로 반올림이 필요해보임

**Comment by dev-manager** [comment]
<h6> 해결! </h6>
